### ISSUE TITLE
Prepare this repo for Harvard Forest Data

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/HarvardMortality#1]
@rudeboybert , @ValentineHerr , I've copied the SCBI repo and deleted most SCBI-specific files, without touching the scripts or testthat folders. I did modify the list of tests to indicate those that should be counted as core (i.e., relevant at HF) and those that are SCBI add-ons.

I need to take a break now... feel free to work on this.

**Comment by rudeboybert** [comment]
Hey Krista, thanks for setting this up. I'm on it

**Comment by teixeirak** [comment]
- The raw data (from FastField) portion of setup should now be complete.
- We do not yet have any GitHub actions set up (@rudeboybert , you'll do that, right?)
- Some of the tests will not work
- making maps will not work

**Comment by rudeboybert** [comment]
- Thanks
- Just done
- I'll comment the code for these tests out as I make a first pass through (will create new issue)
- I commented this part of the GA workflow out in f39c4957dadbcd1c27b0bdacfe7b6294d66d0bed
