### ISSUE TITLE
Committing data 

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#11]
I bypassed the compressed zip and pushed directly the merged excel file. This will be replaced each day with just new data or should it be for all completed stems (cumulative data)?

**Comment by teixeirak** [comment]
It should be the cumulative data. Bypassing the zip could have messed things up.

@rudeboybert is working on this, but I will try re-downloading to make sure we have the file right.

**Comment by teixeirak** [comment]
Nevermind, it appears to have worked!
