### ISSUE TITLE
error is status_AU_DS_or_DC_but_no_FAD for previously dead stems 

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#13]
Can this error message be specific to stems that were previously alive (Status.census.2 = "A")? There aren't any Status.census.2 = "AU."

**Comment by teixeirak** [comment]
I updated the list of tests (this commit: https://github.com/SCBI-ForestGEO/HarvardMortality/commit/93872f4d3bdd8772a62fd12741a7a98d4aeaee89). This change will need to be coded -- both here and for SCBI (@rudeboybert / @ValentineHerr ).

**Comment by mageeluke** [comment]
Awesome, thank you. Can I reupload data from yesterday (2021-07-08)?

**Comment by teixeirak** [comment]
It's not fixed in the code yet, but when it is fixed the tests will re-run automatically.

**Comment by rudeboybert** [comment]
Hey @mageeluke thanks for bringing this to our attention. the code has been updated and the number of `status_AU_DS_or_DC_but_no_FAD` errors in `require_field_fix_error_file.csv` has dropped significantly to only 3. Going forward feel free to update the FFF data anytime you like, filing any issues accordingly.
