### ISSUE TITLE
Duplicate stems

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#15]
We are wondering how duplicated stems are auto-fixed. Does it take the first record? We have conflicting results with a few of them. Also, is there a list of missed stems?

**Comment by teixeirak** [comment]
In cases of duplicates, I believe we're taking the later of two records. But there's  a modification to that in [this issue](https://github.com/SCBI-ForestGEO/SCBImortality/issues/25). I don't believe @ValentineHerr  has coded that yet, have you?

Regarding missed stems, I believe we're still waiting on a list of expected stems from @jess-shue --either that or it just needs coding (@rudeboybert ).

**Comment by rudeboybert** [comment]
The list of missing stems would be generated from the HF census data correct? If so, this is related to #3

**Comment by rudeboybert** [comment]
Hi @mageeluke as you suggested in #16, both records of duplicated stems will now be included in all `require_field_fix_error_file.csv` reports. I'm almost done PR #17 that will address this
