### ISSUE TITLE
Post 07-10-2021 Observations 

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#16]
Our notes from yesterday on fixes to report output: 

- [x] Can we please move all duplicated stems to "requires_field_fix"
- [x] Add dates to error report (merge on submission ID)
- [x] Missing stems still not appearing as field checks
- [x] Some stems were mistakenly marked as dead in 2019 (Status.census.2 = "D") and are now alive --these appear in the warnings. However, other times we accidentally select "A" or possibly observe the wrong crown (if densely crowded). To resolve this, I suggest we move these stems to "requires_field_fix"  if, and only if, no notes are provided. If ANY notes are provided (e.g., " previously dead tree clearly alive"), we could keep as warnings. 

Added by @rudeboybert 
- [x] At HF StemTag uniquely identifies stems, whereas at SCBI it's Tag+StemTag. Accordingly Tag was removed from Fast Fields; a little finessing of code and trace of reports was needed
- [x] Need to add check that personnel is entered (this will also be hard-coded in Fast Field app #18)

**Comment by teixeirak** [comment]
>     3\. Missing stems still not appearing as field checks

We need the list of stems expected. See issue #3.

The others should be fairly easy. Can you program these, @rudeboybert ?

**Comment by djj4tree** [comment]
I have uploaded the stem tag number vector to the data folder. This should allow you to check for missing or duplicates in each quadrat.

**Comment by rudeboybert** [comment]
Hey folks, these have all just been merged in #18. On top of checklist at top of message, some highlights:

1. Missing stems reports are now being written to `reports/requires_field_fix/quadrat_censused_missing_stems.csv`. Note the details are sparse b/c the [`HFmort_stemtag.txt](https://github.com/SCBI-ForestGEO/HarvardMortality/blob/main/data/HFmort_stemtag.txt) file is sparse
1. The "mortality survey completion status" is now live on the README. HF is now 12% done!
