### ISSUE TITLE
Require personnel in Fast Fields

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/HarvardMortality#18]
Hey @jess-shue in case you haven't already, could you update Fast Field so that Personnel is a required field? I actually forgot to select myself a few times on Saturday. I'll also make this an explicit test in GitHub Actions

**Comment by jess-shue** [comment]
@rudeboybert that change will be implemented this morning. Just waiting to confirm with @djj4tree a few other things before updating the app.

**Comment by djj4tree** [comment]
This is now implemented and I will close this issue
