### ISSUE TITLE
Moving to a private repository 

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#19]
As we progress with the mortality census, we will adding more data to the repository; eventually, all stems >= 1 cm will be available (upon completion). The HF data are not ready to distribute and we are concerned about its public availability. What would be the best solution to resolving this? Could we simply hide the data or do we need to move to a private repository?

**Comment by rudeboybert** [comment]
I'm fine with doing that. If @teixeirak @ValentineHerr don't object by today at 5pm, I'll make this repo private

**Comment by ValentineHerr** [comment]
That is fine with me, and I don't think the tests will use up tall the Github actions time allocations.

**Comment by teixeirak** [comment]
It's fine to make it private. It's good to hear that @ValentineHerr doesn't think we'll run out of the GitHub actions credits. If we do, we'd have to pay for more.
