### ISSUE TITLE
Error generating report 

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#25]
It looks like an error came up in the report generation. I think it is the same issue with the column names from 07/10/2021 @rudeboybert.

**Comment by rudeboybert** [comment]
ok on it

**Comment by rudeboybert** [comment]
Thanks for the heads up @mageeluke, I fixed this issue in ffe16b59aaad9a4f9663c7dbe8b6a077b92173ec. Just some misplaced curly braces
