### ISSUE TITLE
Processing error 2021_07_14

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/HarvardMortality#27]
It looks like there was an error with the report generation --exit code 1. @rudeboybert I'm not sure this is the same error that we previously encountered?

**Comment by djj4tree** [comment]
It looks like the auto generate reports is turned off so I did it locally and pushed it back to github.
Closing issue.

**Comment by rudeboybert** [comment]
Hey @djj4tree, actually there was a bug in the script. I fixed in 0efae5b096b650e743b3bb819dda9b55f3811318 and just pushed. GitHub Actions should re-generate the reports (which I think will be the same as your locally created ones)

**Comment by rudeboybert** [comment]
As for the auto generate being turned off, it's only the `R_scripts/Generate_daily_progress_reports.R` in ​the [GitHub Actions YAML file](https://github.com/SCBI-ForestGEO/HarvardMortality/blob/main/.github/workflows/data-tests.yaml). The output of this script is in the bottom of the README which before July 25th I will periodically update manually.
