### ISSUE TITLE
Set up components requiring Harvard Forest census data (?)

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/HarvardMortality#3]
@ValentineHerr , @rudeboybert tells me that the census data and species list are required for the SCBI Mortality repo tests. Where?

I don't currently see why we'd need those (and am not sure it would be okay to put them in a public repo). We do obviously need the list of trees in the census, along with their quadrats and coordinates (if we're to make maps).

Please let us know exactly what's needed, and then we can work with @jess-shue and others to get those data.

**Comment by teixeirak** [comment]
I'd add that it would be nice to be able to make the dashboard map for Harvard Forest, but obviously not essential to having the continuous integration functioning.

**Comment by ValentineHerr** [comment]
@teixeirak,
The only reason we need those is to know the %census completed (main census data) and potential typos in the species names (species list - this is a test I added when I saw some errors but we can easily remove this test).

A list of trees in the census, along with their quadrats would be fine if we can't have the main census data public.
To do the map, we need a shapefile of the quadrats (with quadrat ID as attributes) and make sure we get the quadrat names in the FFF outputs.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr ! So none of this is essential to the core functionality, but would be nice to include if it's not complicated. @rudeboybert is interested in putting map sequences in his paper, so that's some additional motivation to add those (although I think the SCBI sequence would be better).

@jess-shue , can we get the list of trees in the census? And do you have a shapefile of the quadrats?

**Comment by ValentineHerr** [comment]
(I added a [folder in the SCBI repo](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat/reports/sequence_of_maps), to keep track of maps over time, for @rudeboybert map sequences)

**Comment by jess-shue** [comment]
@teixeirak I do not have a shapefile of the quadrats for HF. There are some GIS layers you can download from HF's website, but they do not include a polygon of the ForestGEO plot. I could make one, but it may not be 100% correct. You want the trees only in the mortality survey, correct?

**Comment by teixeirak** [comment]
Yes, we want the trees only in the mortality survey.

**Comment by teixeirak** [comment]
The map is not essential. With it, we could produce a dashboard like this one: 

<img width="713" alt="image" src="https://user-images.githubusercontent.com/6355854/124668895-87790400-de7f-11eb-991b-4d4b3c4dc220.png">

That's convenient but non-essential. It sounds like it may take more time to make this than the time that will be saved by this convenience, so I'd probably skip it.

**Comment by rudeboybert** [comment]
Agreed that focus should only be on what's essential for now. I disabled for now the part of the workflow that creates the maps in f39c4957dadbcd1c27b0bdacfe7b6294d66d0bed; this will still leave the current map up as a preview however (note added to README)

**Comment by teixeirak** [comment]
> You want the trees only in the mortality survey, correct?

@jess-shue or @mageeluke , can you please provide this list? That's needed to get the list of missed trees and calculate % completion (issue #16 ).

**Comment by jess-shue** [comment]
@teixeirak and @rudeboybert There is a file I uploaded in the data folder 6 days ago that is the background data for the FFF's app:  Harvard_mortality_stems_2021.csv.

Also, would a simple grid created in R work for the visual map? I have not gotten coordinates from Dave, but it seems we shouldn't have to have a shapefile to make the progress map, correct?

**Comment by jess-shue** [comment]
@teixeirak and @rudeboybert  Actually, realizing this is a public repository and not all of the data are available from Harvard yet (this is based on second census data that aren't 'out' just yet) we're going to remove that file and Dan will send a list of stems.
Sorry about that!

**Comment by mageeluke** [comment]
I have removed "Havard_mortality_stems_2021.csv." If possible, could we please use the list of stems that Dan has provided: https://github.com/SCBI-ForestGEO/HarvardMortality/blob/main/data/HFmort_stemtag.txt

**Comment by teixeirak** [comment]
Thanks for the tree list (and sorry I missed the fact that you'd loaded one earlier, @jess-shue ). That should work.

And yes, a simple grid created in R would work for the progress map.

**Comment by djj4tree** [comment]
I am working on the progress mapping code for Harvard Forest and should have it ready to go this afternoon. 2021-07-12

**Comment by djj4tree** [comment]
I have now completed the mapping generation script.  Can we get it added back into the processing workflow? @rudeboybert

**Comment by rudeboybert** [comment]
@djj4tree yep, I'll do that rn

**Comment by rudeboybert** [comment]
@djj4tree Added! We now have a completion map on the README dashboard! 🐲🐉

**Comment by teixeirak** [comment]
I love it! Nice work @djj4tree and @rudeboybert !
