### ISSUE TITLE
Disable tests that are specific to SCBI

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/HarvardMortality#4]
In [list of tests](https://github.com/SCBI-ForestGEO/HarvardMortality/blob/main/testthat/list%20of%20tests.md), disable tests where "core or SCBI add-on?" column value is "SCBI"

**Comment by teixeirak** [comment]
looks like this is done...

**Comment by rudeboybert** [comment]
Note for future: maybe master version of `generate_reports.R` into:
1. `generate_reports.R` 
2. `generate_reports_scbi.R`

to make it easier to keep track of changes
