### ISSUE TITLE
`crown_living_greater_than_crown_intact` test has bug

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/HarvardMortality#5]
@rudeboybert , 

The `crown_living_greater_than_crown_intact` test has a bug. Looks like it's reversed. It's reporting an error when `Percentage.of.crown.intact` > `Percentage.of.crown.living` (e.g., stem tag 10028 in [this file](https://github.com/SCBI-ForestGEO/HarvardMortality/blob/main/testthat/reports/requires_field_fix/require_field_fix_error_file.csv)).

**Comment by teixeirak** [comment]
Note that this is not a problem at SCBI

**Comment by rudeboybert** [comment]
Note for future: Issue was caused by `Percentage.of.crown.intact` and `Percentage.of.crown.living` being read as characters and not numerics. Might need to explicit with `read_xlsx(col_types = ...)` in future to prevent this.
