### ISSUE TITLE
tests aren't running on new data file

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/HarvardMortality#9]
@rudeboybert , the tests aren't running on the first field data file (just uploaded). At first the dummy file was in there, so I deleted it. When that didn't work, I deleted the results and data file and then re-loaded the data, but that also didn't work.

**Comment by rudeboybert** [comment]
(for future records) The issue is sometimes caused by conflicts between new versions of reports and new ones, so deleting the old ones often does the trick. I see however you figure this out on your own before merging #12
